<?php

require_once '../includes/auth.php';
requireAdmin();
require_once '../includes/db.php';
require_once '../vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();
$options->setIsRemoteEnabled(true);
$options->setIsHtml5ParserEnabled(true);

$dompdf = new Dompdf($options);

// ==========================
// Report Filters
// ==========================
$from    = $_GET['from'] ?? '';
$to      = $_GET['to'] ?? '';
$student = $_GET['student'] ?? '';
$status  = $_GET['status'] ?? '';

$sql = "
SELECT
    ir.transaction_id,
    s.full_name,
    b.title,
    ir.issue_date,
    ir.due_date,
    ir.return_date,
    ir.status,
    ir.fine
FROM issue_return ir
INNER JOIN student s
    ON ir.student_id = s.student_id
INNER JOIN book b
    ON ir.book_id = b.book_id
WHERE 1
";

$params = [];
$types = "";

// From Date
if (!empty($from)) {
    $sql .= " AND ir.issue_date >= ?";
    $params[] = $from;
    $types .= "s";
}

// To Date
if (!empty($to)) {
    $sql .= " AND ir.issue_date <= ?";
    $params[] = $to;
    $types .= "s";
}

// Student
if (!empty($student)) {
    $sql .= " AND ir.student_id = ?";
    $params[] = $student;
    $types .= "i";
}

$sql .= " ORDER BY ir.issue_date DESC";
$stmt = $conn->prepare($sql);

if (!empty($params)) {
    $stmt->bind_param($types, ...$params);
}

$stmt->execute();
$reportResult = $stmt->get_result(); 

// Summary Statistics
// ==========================

$totalTransaction = $reportResult->num_rows;

$totalIssued = $conn->query("
SELECT COUNT(*) total
FROM issue_return
WHERE status='Issued'
")->fetch_assoc()['total'];

$totalReturned = $conn->query("
SELECT COUNT(*) total
FROM issue_return
WHERE status='Returned'
")->fetch_assoc()['total'];

$totalOverdue = $conn->query("
SELECT COUNT(*) total
FROM issue_return
WHERE status='Issued'
AND due_date < CURDATE()
")->fetch_assoc()['total'];

$totalFine = $conn->query("
SELECT IFNULL(SUM(fine),0) total
FROM issue_return
")->fetch_assoc()['total'];

$logo = base64_encode(file_get_contents("../assets/images/logo.png"));

$html = '

<style>

body{
    font-family: DejaVu Sans, sans-serif;
    font-size:16px;
}

body{
    font-family: DejaVu Sans, sans-serif;
    font-size:16px;
}

h1{
    margin:0;
    font-size:22px;
}

h3{
    margin:5px 0 0;
    font-size:14px;
}

table{
    width:100%;
    border-collapse:collapse;
}

thead {
    display: table-header-group;
}

tfoot {
    display: table-footer-group;
}

th{
    background:#0d6efd;
    color:#fff;
    border:1px solid #ccc;
    padding:10px 8px;
    font-size:16px;
}

td{
    border:1px solid #ccc;
    padding:8px;
    font-size:14px;
}

tr:nth-child(even){
    background:#f8f9fa;
}

.date{
    margin-top:20px;
    text-align:center;
    font-weight:bold;
}

.footer{
    margin-top:20px;
    text-align:right;
    font-weight:bold;
}

</style>';

$html .= '

<div style="
background:#0d6efd;
color:white;
padding:12px;
border-radius:6px;
">

<table style="width:100%;border:none;">

<tr>

<td style="border:none;width:90px;">

<img src="data:image/jpeg;base64,'.$logo.'" width="70">

</td>

<td style="border:none;text-align:center;color:white;">

<h1 style="color:white;">
ONLINE LIBRARY SYSTEM
</h1>

<h3 style="color:white;">
Library Transaction Report
</h3>

</td>

</tr>

</table>

</div>

</div>

';

$html .= '

<table style="
width:100%;
margin-top:15px;
border:none;
">

<tr>

<td style="border:none;
font-size:16px;">

<b>Generated On :</b>

'.date("d F Y h:i A").'

</td>

<td style="border:none;
text-align:right;
font-size:16px;
">

<b>Generated By :</b>

Administrator

</td>

</tr>

</table>

';

$html .= '

<h3 style="
background:#eeeeee;
padding:8px;
margin-top:20px;
font-size:16px;
">
Summary
</h3>

<table>

<tr>

<th style="width:20%;">Total Transactions</th>
<th style="width:20%;">Issued</th>
<th style="width:20%;">Returned</th>
<th style="width:20%;">Overdue</th>
<th style="width:20%;">Total Fine</th>

</tr>

<tr style="text-align:center;">

<td>'.$totalTransaction.'</td>
<td>'.$totalIssued.'</td>
<td>'.$totalReturned.'</td>
<td>'.$totalOverdue.'</td>
<td>Rs. '.number_format($totalFine,2).'</td>

</tr>

</table>
<br/>
';

$html .= '

<table>
<thead>
<tr>
    <th style="width:40px; text-align:center;">S.N.</th>
    <th style="width:180px;">Student Name</th>
    <th style="width:200px;">Book Title</th>
    <th style="width:105px; text-align:center;">Issue Date</th>
    <th style="width:90px; text-align:center;">Due Date</th>
    <th style="width:110px; text-align:center;">Return Date</th>
    <th style="width:110px; text-align:center;">Status</th>
    <th style="width:60px;">Fine</th>
</tr>
</thead>
<tbody>

';

$sn = 1;

while($row = $reportResult->fetch_assoc()){

    if($row['status']=="Issued"){

        $status = '<span style="color:#dc3545;font-weight:bold;">ISSUED</span>';

    }
    elseif($row['status']=="Returned"){

        $status = '<span style="color:#198754;font-weight:bold;">RETURNED</span>';

    }
    else{

        $status = '<span style="color:#fd7e14;font-weight:bold;">OVERDUE</span>';

    }

    $html .= '

    <tr>

        <td style="text-align:center;">'.$sn++.'</td>

        <td>'.htmlspecialchars($row['full_name']).'</td>

        <td>'.htmlspecialchars($row['title']).'</td>

        <td style="text-align:center;">
            '.date("d M Y", strtotime($row['issue_date'])).'
        </td>

        <td style="text-align:center;">
            '.date("d M Y", strtotime($row['due_date'])).'
        </td>

        <td style="text-align:center;">
            '.($row['return_date']
                ? date("d M Y", strtotime($row['return_date']))
                : "-").'
        </td>

        <td style="text-align:center;">
            '.$status.'
        </td>

        <td style="text-align:right;">
            Rs. '.number_format($row['fine'],2).'
        </td>

    </tr>

    ';

}

$html .= '

</tbody>
</table>

<br>
<hr>

<div style="
    margin-top:15px;
    font-size:16px;
">

    <span style="float:left;">
        Generated by Online Library System
    </span>

    <span style="float:right;">
        Printed on '.date("d F Y").'
    </span>

    <div style="clear:both;"></div>

</div>

';

$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();

$canvas = $dompdf->getCanvas();

$canvas->page_text(
700,
565,
"Page {PAGE_NUM} of {PAGE_COUNT}",
null,
10,
array(0,0,0)
);

$dompdf->stream(
    "reports.pdf",
    ["Attachment" => true]
);



?>